plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

paginate: 100
paginate_path: "page/:num"
baseurl: "/"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]

title: "جملات انگیزشی"
email: mhkaram97@gmail.com
description: "جملات انگیزشی"

github:
  username: mhkarami97

swiftype:
  searchId: "3cGh6TzuZUfyZMsybLKx"

# gitment:
#     repo: blog
#     client_id: a6fb73b3e790e234bab8
#     client_secret: cc10aaff53a03d05ab2ee002dbf401dd7627c7a3

url: "https://sentence.mhkarami97.ir"
imgrepo: "https://sentence.mhkarami97.ir/static/img"

google_analytics: "G-2KGKGYQR60"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-2KGKGYQR60"
    anonymize_ip: false # default
